source "https://rubygems.org"

gem "rails", "~> 7.1.5"
gem "mongoid", "~> 9.0"
gem "puma", "~> 6.4"
gem "redis", "~> 5.0"
gem "rack-cors"
gem "bcrypt", "~> 3.1"

group :development do
  gem "listen"
end
